### ISSUE TITLE
在vue 中引入报错，找不到依赖

### ISSUE THREAD

**Issue by heda20** [trionfo1993/vue2-verify#1]
1 首先 通过 npm i vue2-verify 安装 
2 在 所在的组件中 通过 
import Verify from 'vue2-verify';
查看node_modules 有此包
但是说找不到依赖 。求解，本人新手一枚

**Comment by trionfo1993** [comment]
试试加 --save 老版npm的不会加入到依赖里

**Comment by shenxinbo** [comment]
![image](https://user-images.githubusercontent.com/1240864/35803648-83d6cba4-0aaf-11e8-8a8b-3cd4c771b19d.png)
同上

**Comment by shenxinbo** [comment]
![image](https://user-images.githubusercontent.com/1240864/35803723-c58ea74c-0aaf-11e8-9300-5173a41e1d7b.png)

**Comment by shenxinbo** [comment]
![image](https://user-images.githubusercontent.com/1240864/35803851-470d39be-0ab0-11e8-8619-bdb4680207cb.png)

**Comment by trionfo1993** [comment]
已经修复
