### ISSUE TITLE
希望能在配置项中添加是否显示插件自带的按钮

### ISSUE THREAD

**Issue by chenweibo** [trionfo1993/vue2-verify#11]
因为有时候引用插件的时候不需要自带的这个button 我还需要手动去包里面改 很多次。  希望能不能自定义配置这个。

**Comment by chenweibo** [comment]
@mizuka-wu  滑块类型的。

**Comment by chenweibo** [comment]
<img width="407" alt="2019-01-03 8 54 52" src="https://user-images.githubusercontent.com/19586007/50619639-4cf02280-0f35-11e9-84fc-c77ad7c27181.png">

**Comment by wwLovejy** [comment]
> 因为有时候引用插件的时候不需要自带的这个button 我还需要手动去包里面改 很多次。 希望能不能自定义配置这个。

我也遇到这个问题，希望作者加个是否显示底部按钮的配置，
