### ISSUE TITLE
为啥会带着个确认按钮呢

### ISSUE THREAD

**Issue by zcwk** [trionfo1993/vue2-verify#3]

**Comment by leochan2017** [comment]
同问，一切都好，就是带这个就好别扭了。特别type=3的时候也有确定按钮

**Comment by trionfo1993** [comment]
因为只移了逻辑部分 其余的都是照搬原始项目的

**Comment by trionfo1993** [comment]
讲道理 没太在意样式 主要把jquery转vue的都是那些验证部分

**Comment by leochan2017** [comment]
soga

**Comment by leochan2017** [comment]
success和error事件是通过这个确定按钮触发的 - - !

**Comment by trionfo1993** [comment]
阿哈哈哈哈 请随意修改 毕竟这只是个demo

发自我的 iPhone

在 2018年5月28日，下午10:41，Leo <notifications@github.com<mailto:notifications@github.com>> 写道：


success和error事件是通过这个确定按钮触发的 - - !
