### ISSUE TITLE
使用正常，打包报错

### ISSUE THREAD

**Issue by fffyang** [trionfo1993/vue2-verify#4]
你好，我使用验证码组件的时候正常运行，但是打包的时候就会报错，无法使用。
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/37098927/43191312-87be3820-902d-11e8-8813-b61b79f3dd63.png">

**Comment by trionfo1993** [comment]
Webpack打包请把项目babel或者js的include内

**Comment by trionfo1993** [comment]
Webpack打包请把项目添加到babel或者js的include内

**Comment by trionfo1993** [comment]
webpack 配置里有个loaders，里面的.js的配置里加一个include这个项目
更加建议直接复制源码修改，毕竟这个项目只是一个jquery的实现版，不是组件库

**Comment by trionfo1993** [comment]
[链接](https://blog.csdn.net/u010394015/article/details/79140720)
[链接](https://www.cnblogs.com/vok-think/p/8287433.html)
看一下这两个，打包的时候没有转换es6语法的问题

**Comment by fffyang** [comment]
你好，我已经尝试打包成功了，但是报了一个警告，不知是否有影响呢？
<img width="919" alt="image" src="https://user-images.githubusercontent.com/37098927/43236540-372b5704-90b8-11e8-8f84-1f21a77e3ddf.png">

**Comment by fffyang** [comment]
ok,已经成功了，谢谢
