### ISSUE TITLE
IE9下报错

### ISSUE THREAD

**Issue by Zoidbergme** [trionfo1993/vue2-verify#7]
项目用的框架是VUE，然后在IE9之中报错语法错误，看了下，是utils.js里面的const没被转成es5，改成
var  _code_chars = [1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
var _code_color1 = ['#fffff0', '#f0ffff', '#f0fff0', '#fff0f0']
var _code_color2 = ['#FF0033', '#006699', '#993366', '#FF9900', '#66CC66', '#FF33CC']
export {_code_chars,_code_color1,_code_color2} 就好了

**Comment by trionfo1993** [comment]
webpack将这个项目也加到babel下就行了哦
